config/routes.rb
Parsings::Application.routes.draw do

  root 'shop#index'
  resources :shops

end

app/models/catalog_shop.rb
class CatalogShop < ActiveRecord::Base
  has_many :products
end

app/models/extra_prop.rb
class ExtraProp < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/price.rb
class Price < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :prices
  has_many :photos
  belongs_to :shop
  belongs_to :catalog_shop
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :products
  has_many :catalog_shops
  validates :name, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # для получения контента через http
  require 'open-uri'
  # подключаем Nokogiri
  require 'nokogiri'

  def index
    source = 'http://catalog.yandex.ru/'

    # получаем содержимое веб-страницы в объект
    page = Nokogiri::HTML(open(source.to_s + page))

    # производим поиск по элементам с помощью css-выборки
    page.css('a.b-rubric__list__item__link').each do |link|

      data = Hash.new

      data['text'] = link.content

      data['href'] = link['href']

    end
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shop=Shop.all
  end

  def show
    @shop=Shop.find(params[:id])
  end

  def new
    @shop=Shop.new
  end

  def create
    @shop=Shop.new(shop_params)

    if @shop.save
      redirect_to @shop
    else
      render 'new'
    end
  end

  def edit
    @shop=Shop.find(params[:id])
  end

  def update
    @shop=Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to @shop
    else
      render 'edit'
    end
  end

  def destroy
    @shop=Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
  end

  private
  def shop_params
            params.require(:shop).permit(:name,:url,:xpath,:host)
          end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/home/index.html.erb
dsfasdf

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parsings</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shops/index.html.erb
<h1>Список сайтов</h1>
<%= link_to 'Добавить сайт', new_shop_path %>
<table>
  <tr>
    <th>Название</th>
    <th>Url</th>
    <th>Xpath</th>
    <th>Host</th>
  </tr>

  <% @shop.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.url %></td>
        <td><%= shop.xpath %></td>
        <td><%= shop.host %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop_path(shop),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>